apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-affinity
spec:
  affinity:
    podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: app-name
      #     - key: app-nameee # This is "HARD RULE" as lable will not match and it will be in pending state.
      #       operator: In
      #       values:
      #       - pod-1
      #   topologyKey: "kubernetes.io/hostname"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app-nameee # This is the "SOFT RULE" if labels are not matched, then scheduler schedules on to some other node. 
              operator: In
              values:
              - pod-1
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: pod-2
    image: nginx